controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# controllers:
#     resource: ../src/Controller/
#     type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation